version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Files stored in repository root
    directory: '/'
    # Check for updates every weekday
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "UTC"
    # Add assignees
    assignees:
      - 'nekofar'
    # Include a list of updated dependencies
    commit-message:
      prefix: 'ci'
      include: 'scope'
    # Specify labels for pull requests
    labels:
      - 'dependencies'
    # Allow up to 20 open pull requests for dependencies
    open-pull-requests-limit: 20
    # Add reviewers
    reviewers:
      - 'nekofar'
    # Raise pull requests against the `develop` branch
    target-branch: 'develop'

  # Maintain dependencies for PNPM
  - package-ecosystem: 'npm'
    # Files stored in repository root
    directory: '/'
    # Check for updates every weekday
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "UTC"
    # Add assignees
    assignees:
      - 'nekofar'
    # Include a list of updated dependencies
    commit-message:
      prefix: 'chore'
      include: 'scope'
    # Specify labels for pull requests
    labels:
      - 'dependencies'
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 20
    # Add reviewers
    reviewers:
      - 'nekofar'
    # Raise pull requests against the `develop` branch
    target-branch: 'develop'
    # Create a group of dependencies to be updated together in one pull request
    groups:
      eslint:
        patterns:
          - 'eslint'
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
